site_name: Rusty Web
site_description: Rusty Web is a lightweight web framework for rust developers.
repo_url: https://github.com/tejmagar/rusty-web
edit_uri: ./edit/main/docs

nav:
  - Getting Started: README.md

